# Generated by Django 4.2.27 on 2025-12-25 18:30

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Contact page description and information'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=50),
        ),
    ]
