# Generated by Django 4.2.27 on 2025-12-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('home', '0003_remove_contactpage_address_remove_contactpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_background',
            field=models.ForeignKey(blank=True, help_text='Hero section background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
