# Generated by Django 4.2.27 on 2025-12-25 18:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Text to describe the products page')),
            ],
            options={
                'verbose_name': 'Products Listing Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='productindexpage',
            options={'verbose_name': 'Product Category Page'},
        ),
        migrations.AlterField(
            model_name='productindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to describe this product category'),
        ),
    ]
