# Generated by Django 4.2.27 on 2025-12-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('products', '0002_productslistingpage_alter_productindexpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindexpage',
            name='cover_photo',
            field=models.ForeignKey(blank=True, help_text='Cover photo/hero image for this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='specification_pdf',
            field=models.ForeignKey(blank=True, help_text='Product specification PDF', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
